apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-03-01T11:39:17Z"
  generation: 4
  labels:
    app: hello-kubernetes
  name: hello-kubernetes
  namespace: default
  resourceVersion: "1659"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hello-kubernetes
  uid: 777cd400-1f18-4d86-b274-dd51d6dae7b8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - image: capnajax/hello-kubernetes
        imagePullPolicy: Always
        name: hello-kubernetes
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
